# datasource config
spring:
  datasource: 
    url: jdbc:mysql://10.1.110.21:3306/cqrs
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 111111
    validation-query: SELECT 1;
    initial-size: 2
    sql-script-encoding: UTF-8
  jpa:
    database: mysql
    show-sql: true
    hibernate.ddl-auto: create-drop
  # mq for event bus
  rabbitmq:
    host: 112.124.34.47
    port: 5672
    username: axon
    password: axon

# mongo for query
mongo:
  url: 112.124.34.47
  port: 27017
  dbname: axon

# enable axon Amqp support
axon:
  amqp:
    exchange: Axon.EventBus
  distributed:
    jgroups:
      enabled: true
      gossip:
        autoStart: true